set wshshell = wscript.createobject("wscript.shell")
Wshshell.run "Notepad"
wscript.sleep 400
wshshell.sendkeys "C"
wscript.sleep 100
wshshell.sendkeys "o"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "e"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 200
wshshell.sendkeys " "
wscript.sleep 200
wshshell.sendkeys "b"
wscript.sleep 100
wshshell.sendkeys "y"
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys "M"
wscript.sleep 200
wshshell.sendkeys "a"
wscript.sleep 200
wshshell.sendkeys "r"
wscript.sleep 100
wshshell.sendkeys "k"
wscript.sleep 200
wshshell.sendkeys "."
wscript.sleep 200
wshshell.sendkeys "{ENTER}"
wscript.sleep 100
wshshell.sendkeys "W"
wscript.sleep 100
wshshell.sendkeys "a"
wscript.sleep 100
wshshell.sendkeys "i"
wscript.sleep 100
wshshell.sendkeys "t"
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys "t"
wscript.sleep 100
wshshell.sendkeys "i"
wscript.sleep 100
wshshell.sendkeys "l"
wscript.sleep 100
wshshell.sendkeys "l"
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys "p"
wscript.sleep 100
wshshell.sendkeys "r"
wscript.sleep 100
wshshell.sendkeys "o"
wscript.sleep 100
wshshell.sendkeys "c"
wscript.sleep 100
wshshell.sendkeys "e"
wscript.sleep 100
wshshell.sendkeys "s"
wscript.sleep 100
wshshell.sendkeys "s"
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys "i"
wscript.sleep 100
wshshell.sendkeys "s"
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "o"
wscript.sleep 100
wshshell.sendkeys "n"
wscript.sleep 100
wshshell.sendkeys "e"
wscript.sleep 100
wshshell.sendkeys ","
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys "E"
wscript.sleep 100
wshshell.sendkeys "n"
wscript.sleep 200
wshshell.sendkeys "j"
wscript.sleep 200
wshshell.sendkeys "o"
wscript.sleep 100
wshshell.sendkeys "y"
wscript.sleep 100
wshshell.sendkeys "!"
wscript.sleep 400
wshShell.Sendkeys "{ENTER}"
wshShell.Sendkeys "{ENTER}"
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshShell.Sendkeys "{ENTER}"
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshShell.Sendkeys "{ENTER}"
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshShell.Sendkeys "{ENTER}"
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshShell.Sendkeys "{ENTER}"
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
WshShell.Sendkeys "{ENTER}"
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "_"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "$"
wscript.sleep 100
wshshell.sendkeys "{ENTER}"